gestion/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^minierp/', include('minierp.urls')),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/logout/$', auth_views.logout,  {'next_page': '/'}, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

minierp/urls.py
from __future__ import unicode_literals
from django.conf.urls import url, include
from minierp.views import *


urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^tva/$', AddTva.as_view(), name='add-tva'),
    url(r'^tva/delete/(?P<pk>\d+)$', DeleteTva.as_view(), name='delete-tva'),
    url(r'^clients/$', ClientList.as_view(), name='client-list'),
    url(r'^clients/create/', ClientCreate.as_view(), name='client-create'),
    url(r'^clients/edit/(?P<pk>\d+)$', ClientEdit.as_view(), name='client-edit'),
    url(r'^clients/detail/(?P<pk>\d+)$', ClientDetail.as_view(), name='client-detail'),
    url(r'^clients/delete/(?P<pk>\d+)$', ClientDelete.as_view(), name='client-delete'),
    url(r'^client-autocomplete/$', ClientAutocomplete.as_view(), name='client-autocomplete'),
    url(r'^client-data/$', get_client_data, name='get_client_data'),

    url(r'^factures/$', FactureList.as_view(), name='facture-list'),
    url(r'^factures/create/$', facture_create, name='facture-create'),
    url(r'^factures/edit/(?P<pk>\d+)$', facture_edit, name='facture-edit'),
    url(r'^factures/detail/(?P<pk>\d+)$', FactureDetail, name='facture-detail'),
    url(r'^factures/delete/(?P<pk>\d+)$', FactureDelete.as_view(), name='facture-delete'),

    url(r'^devis/$', DevisList.as_view(), name='devis-list'),
    url(r'^devis/create/$', devis_create, name='devis-create'),
    # url(r'^devis/edit/(?P<pk>\d+)$', devis_edit, name='devis-edit'),
    url(r'^devis/detail/(?P<pk>\d+)$', DevisDetail, name='devis-detail'),
    # url(r'^devis/delete/(?P<pk>\d+)$', DevisDelete.as_view(), name='devis-delete'),
]

minierp/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone


class Client(models.Model):
    CIVILITES = (
        ('M.', 'M.'),
        ('Mme', 'Mme'),
        ('M. et Mme', 'M. et Mme'),
        ('SARL', 'SARL'),
        ('Domaine', 'Domaine')
    )
    civilite  = models.CharField(max_length=10,choices=CIVILITES, default='M.')
    nom = models.CharField(max_length=255)
    prenom = models.CharField(max_length=255, blank=True)
    adresse = models.CharField(max_length=255, blank=True)
    ville = models.CharField(max_length=255)
    cp = models.IntegerField(blank=True)

    def __unicode__(self):
        return unicode(self.civilite + ' ' + self.nom + ' ' + self.prenom )


class Tva(models.Model):
    value = models.DecimalField(max_digits=4, decimal_places=2)

    def __unicode__(self):
      return unicode(self.value)


class Facture(models.Model):
    date = models.DateField(default=timezone.now)
    id_client = models.ForeignKey('Client')
    add_description = models.TextField(max_length=400, null=True, blank=True)
    acompteht = models.DecimalField(max_digits=8, decimal_places=2, default=0.00)
    acomptettc = models.DecimalField(max_digits=8, decimal_places=2, default=0.00)
    tva = models.ForeignKey('Tva', null=False, blank=False)
    prixht = models.DecimalField(max_digits=8, decimal_places=2, default=0.00)
    prixttc = models.DecimalField(max_digits=8, decimal_places=2, default=0.00)
    dejaregle = models.DecimalField(max_digits=8, decimal_places=2, default=0.00)
    parttva = models.DecimalField(max_digits=8, decimal_places=2, default=0.00)
    netapayer = models.DecimalField(max_digits=8, decimal_places=2, default=0.00)

    def __unicode__(self):
        return unicode(self.id_client)

    def get_client(self):
        return unicode(self.id_client)


class FactureStep(models.Model):
    facture = models.ForeignKey(Facture)
    step_title = models.CharField(max_length=255)
    step_description = models.TextField(max_length=500)

    def __unicode__(self):
        return str(self.step_title)

minierp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import json

from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.db import transaction
from django.forms import formset_factory
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView, View
from django.db.models import Q
from minierp.models import Client, Tva, Facture, FactureStep
from minierp.forms import *
from minierp.pdf import generate_invoice, generate_quote

from dal import autocomplete


def test(request):

    return render(request, 'minierp/test.html')


def home(request):
    context_dict = {}
    # recuperer les derniers clients, devis, factures
    context_dict['client_list'] = Client.objects.order_by('-pk')[:3]
    # context_dict['devis_list'] = Devis.objects.order_by('-pk')[:3]
    context_dict['facture_list'] = Facture.objects.order_by('-pk')[:3]

    return render(request, 'base-minierp.html', context_dict)


class ClientList(ListView):
    model = Client


class ClientCreate(SuccessMessageMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('client-list')
    success_message = u'%(civilite)s %(nom)s %(prenom)s a bien été ajouté.'


class ClientEdit(SuccessMessageMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('client-list')
    success_message = u'%(civilite)s %(nom)s %(prenom)s a bien été modifié.'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(ClientEdit, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['is_edition'] = True
        return context


class ClientDetail(DetailView):
    model = Client


class ClientDelete(SuccessMessageMixin, DeleteView):
    model = Client
    context_object_name = 'obj'
    template_name = "minierp/obj_delete.html"
    success_url = reverse_lazy('client-list')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        client = self.object.__dict__['civilite'] + " " + self.object.__dict__['nom'] + " " +self.object.__dict__['prenom']
        success_message = u'Le client %s a bien été supprimé.' % client
        messages.warning(self.request, success_message)
        return super(ClientDelete, self).delete(request, *args, **kwargs)


class AddTva(SuccessMessageMixin, CreateView):
    model = Tva
    form_class = TvaForm
    success_url = reverse_lazy('add-tva')
    success_message = u'La TVA à %(value)s %% a bien été ajoutée.'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(AddTva, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['tva_list'] = Tva.objects.all()
        return context


class DeleteTva(SuccessMessageMixin, DeleteView):
    model = Tva
    context_object_name = 'obj'
    template_name = "minierp/obj_delete.html"
    success_url = reverse_lazy('add-tva')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_message = u'La TVA %s a bien été supprimée.' % self.object
        messages.warning(self.request, success_message)
        return super(DeleteTva, self).delete(request, *args, **kwargs)


class FactureList(ListView):
    model = Facture
    # paginate_by = 10


class DevisList(ListView):
    model = Devis
    # paginate_by = 10


class ClientAutocomplete(autocomplete.Select2QuerySetView):
    """view for auto-completion of client name in facture form."""
    def get_queryset(self):

        qs = Client.objects.all()
        if self.q:
            qs = qs.filter(Q(nom__istartswith=self.q) |
                           Q(civilite__istartswith=self.q) |
                           Q(prenom__istartswith=self.q))

        return qs


@csrf_exempt
def get_client_data(request):
    id_client = int(request.POST.get('id', ''))
    if id_client:
        client = Client.objects.get(pk=id_client)
        data = {'address': client.adresse, 'cp': client.cp, 'city': client.ville}
        return HttpResponse(json.dumps(data))

    response = {}
    return HttpResponse(json.dumps(response))


# class FactureCreate(CreateView):
#     model = Facture
#     form_class = FactureForm
#     success_url = reverse_lazy('facture-list')
#     success_message = u'La facture a bien été créée.'
#
#     def get_context_data(self, **kwargs):
#         data = super(FactureCreate, self).get_context_data(**kwargs)
#         if self.request.POST:
#             data['descriptions'] = DescriptionFormSet(self.request.POST)
#         else:
#             data['descriptions'] = DescriptionFormSet()
#         return data
#
#     def form_valid(self, form):
#
# def facture_create(request):
#
#         # Get our existing formset data for this facture.  This is used as initial data.
#         # facture_steps = FactureStep.objects.filter(facture=facture.pk)
#         # facture_data = [{'step_title': fs.step_title, 'step_description': l.step_description} for fs in facture_steps]
#         #
#         if request.method == 'POST':
#             facture_form = FactureForm(request.POST)
#             des_formset = DescriptionFormSet(request.POST)
#
#             if facture_form.is_valid() and des_formset.is_valid():
#                 # Save facture info
#                 obj = facture_form.save()
#                 # description_form.instance = self.object
#
#
#             new_des = []
#             # id = facture_form.cleaned_data.get('pk')
#             # id = facture_form.pk
#             for des_form in des_formset:
#                 d = des_form.cleaned_data.get('step_description')
#                 t = des_form.cleaned_data.get('step_title')
#                 # id = des_form.cleaned_data.get('id')
#                 des_form.instance = obj
#                 new_des.append(FactureStep(facture=obj, step_description=d, step_title=t))
#
#             with transaction.atomic():
#                 FactureStep.objects.filter(facture=obj.pk).delete()
#                 x = new_des[0].facture_id
#
#                 FactureStep.objects.bulk_create(new_des)
#
#             messages.success(request, 'You have updated your profile.')
#             return HttpResponseRedirect(reverse_lazy('facture-list'))
#         else:
#             facture_form = FactureForm()
#             des_formset = DescriptionFormSet()
#
#         context = {
#             'form': facture_form,
#             'descriptions': des_formset,
#         }
#
#         return render(request, 'minierp/facture_form.html', context)

def facture_create(request):

    FactureStepFormSet = formset_factory(FactureStepForm, formset=DescriptionFormSet )

    # get existing in case of edition (nothing here in creation)

    if request.method == 'POST':
        facture_form = FactureForm(request.POST)
        facturestep_formset = FactureStepFormSet(request.POST)

        if facture_form.is_valid() and facturestep_formset.is_valid():

            # Save facture info
            f = facture_form.save()
            # description_form.instance = self.object

            new_steps = []
            for facturestep in facturestep_formset:
                d = facturestep.cleaned_data.get('step_description')
                t = facturestep.cleaned_data.get('step_title')

                if d and t:
                    new_steps.append(FactureStep(facture=f, step_description=d, step_title=t))

            with transaction.atomic():
                # Replace the old with the new
                FactureStep.objects.filter(facture=f).delete()
                FactureStep.objects.bulk_create(new_steps)

            messages.success(request, 'La facture n° %d a bien été créée.' % f.pk)
            return HttpResponseRedirect(reverse_lazy('facture-list'))
    else:
        facture_form = FactureForm()
        facturestep_formset = DescriptionFormSet()# put initial data in edition

    context = {
        'form': facture_form,
        'facturestep_formset': facturestep_formset,
        'is_edition': False
    }

    return render(request, 'minierp/facture_form.html', context)


def devis_create(request):

    DevisStepFormSet = formset_factory(DevisStepForm, formset=DescriptionDevisFormSet)

    # get existing in case of edition (nothing here in creation)

    if request.method == 'POST':
        devis_form = DevisForm(request.POST)
        devisstep_formset = DevisStepFormSet(request.POST)

        if devis_form.is_valid() and devisstep_formset.is_valid():

            # Save facture info
            devis = devis_form.save()
            # description_form.instance = self.object

            new_steps = []
            for devisstep in devisstep_formset:
                d = devisstep.cleaned_data.get('step_description')
                t = devisstep.cleaned_data.get('step_title')

                if d and t:
                    new_steps.append(DevisStep(facture=devis, step_description=d, step_title=t))

            with transaction.atomic():
                # Replace the old with the new
                DevisStep.objects.filter(facture=devis).delete()
                DevisStep.objects.bulk_create(new_steps)

            messages.success(request, 'Le devis n° %d a bien été créé.' % devis.pk)
            return HttpResponseRedirect(reverse_lazy('devis-list'))
    else:
        devis_form = DevisForm()
        devisstep_formset = DescriptionFormSet()  # put initial data in edition

    context = {
        'form': devis_form,
        'devisstep_formset': devisstep_formset,
        'is_edition': False
    }

    return render(request, 'minierp/devis_form.html', context)

minierp/templates/minierp/client_detail.html
{% extends "base-minierp.html" %}
{% load staticfiles %}
{% block title %}Fiche client{% endblock title %}

{% block content %}        
  <!-- Page Content -->
  <div class="container">
    <h3 class="text-center">Fiche client n° {{ client.pk }}</h3>
    <div class="row">
      <div class="col-sm-4">
        <img src="{% static 'img/client_avatar.png' %}" class="img-thumbnail" >
      </div>
      <div class="col-sm-8">
        <div class="row">
          <div class="well well-lg">
            <p> {{ client.civilite }} {{ client.nom }} {{ client.prenom }}</p>
            <p> {{ client.adresse }}</p>
            <p> {{ client.cp }} {{ client.ville }}</p>
          </div>
        </div>
        <div class="row">
          <a href="{% url 'client-delete' client.pk %}" class="btn btn-danger pull-left">Supprimer</a>
          <a href="{% url 'client-edit' client.pk %}" class="btn btn-primary pull-right" >Modifier</a>
          <a href="#" class="btn btn-default pull-right">Facturer</a>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

minierp/templates/minierp/client_form.html
{% extends "base-minierp.html" %}
{% load crispy_forms_tags %}

{% block title %}{% if is_edition %}Modifier{% else %}Ajouter{% endif %} un client{% endblock title %}

{% block content %}        
  <!-- Page Content -->
  <div class="container">
      <div class="page-header">
          <div class="row">
              <div class="col-lg-10">
                  <h3>{% if is_edition %}Modification{% else %}Ajout{% endif %} d'un client</h3>
                    {% crispy form %}
              </div>
          </div>
      </div>
  </div>
{% endblock content %}

minierp/templates/minierp/client_list.html
{% extends "base-minierp.html" %}

{% block title %}Liste clients{% endblock title %}


{% block extra_head_content %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css">
{% endblock %}

{% block content %}
<!-- Page Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h3>Liste des clients ({{ client_list.count }})</h3>
      <div class="col-lg-12">
      {% include "messages.html" %}
      {% include "minierp/table_client.html" %}
        </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block extra_script_content  %}
<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>

<script>
$(document).ready(function() {
  $('#example').DataTable({
  "language": {
      "lengthMenu": "Afficher _MENU_ clients par page",
      "zeroRecords": "Aucuns clients trouvés.",
      "info": "Page affichée _PAGE_ sur _PAGES_",
      "infoEmpty": "Pas de clients disponibles",
      "infoFiltered": "(filtré sur _MAX_ clients)"
      }
  });
} );
</script>
{% endblock %}

minierp/templates/minierp/devis_form.html
{% extends "base-minierp.html" %}
{% load bootstrap %}
{% load staticfiles %}

{% block title %}{% if is_edition %}Modifier{% else %}Crééer{% endif %} un devis{% endblock title %}

{% block extra_head_content %}
    <link rel="stylesheet" href="{% static 'css/datepicker.css' %}">
{% endblock extra_head_content %}

{% block content %}
<!-- Page Content -->
<div class="container">
    <div class="page-header">
        <div class="row">
            <div class="col-lg-10">
                <h3>{% if is_edition %}Modifier{% else %}Crééer{% endif %} un devis</h3>

                <form class="form-horizontal" method="post">
                    {% csrf_token %}

                    <legend class="col-form-legend">Client</legend>
                    <div class="form-group row">
                        <div class="col-xs-8">
                            {{ form.id_client }}
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-xs-8">
                            <input type="text" class="form-control" id="id_client_address" placeholder="Adresse" readonly>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-xs-3">
                            <div class="input-group">
                                <input type="text" class="form-control" id="id_client_cp" placeholder="Code Postal" readonly>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="input-group">
                                <input type="text" class="form-control" id="id_client_city" placeholder="Ville" readonly>
                            </div>
                        </div>
                    </div>

                    <legend class="col-form-legend">Détails</legend>

                     <!--<input type="text" class="form-control" id="id_date" placeholder="DAte 2">-->

                     <div class="form-group row">
                        <div class="col-xs-4">
                            <div class="input-group">
                                 {{ form.date|bootstrap_horizontal }}
                            </div>
                        </div>
                    </div>

                    {% for devisstep in devisstep_formset %}
                    <div class="link-formset">
                        {% if devisstep.instance.pk %}{{ devisstep.DELETE }}{% endif %}

                        {{ devisstep|bootstrap_horizontal}}
                        {% comment %}
                        {% if devisstep.step_title.errors %}
                        {% for error in devisstep.step_title.errors %}
                        {{ error|escape }}
                        {% endfor %}
                        {% endif %}

                        {{ devisstep.step_description }}
                        {% if devisstep.step_description.errors %}
                        {% for error in devisstep.step_description.errors %}
                        {{ error|escape }}
                        {% endfor %}
                        {% endif %}
                        {% endcomment %}
                    </div>

                    {% endfor %}
                    {{ devisstep_formset.management_form }}

                    {% if devisstep.non_form_errors %}
                    {% for error in devisstep.non_form_errors %}
                    {{ error|escape }}
                    {% endfor %}
                    {% endif %}

                    {{ form.add_description|bootstrap_horizontal }}

                    <!--<legend class="col-form-legend">Tarification</legend>-->
                    <!--<a class="btn btn-primary" onclick="init_prices()">RAZ</a>-->
                    <!--<div class="form-group row">-->
                        <!--<div class="col-xs-4">-->
                            <!--{{ form.acompteht.label_tag }}-->
                            <!--<div class="input-group">-->
                                <!--{{ form.acompteht }}-->
                                <!--<div class="input-group-addon">€</div>-->
                            <!--</div>-->
                        <!--</div>-->
                        <!--<div class="col-xs-4">-->
                            <!--{{ form.prixht.label_tag }}-->
                            <!--<div class="input-group">-->
                                <!--{{ form.prixht }}-->
                                <!--<div class="input-group-addon">€</div>-->
                            <!--</div>-->
                        <!--</div>-->
                    <!--</div>-->
                    <!--<div class="form-group row">-->
                        <!--<div class="col-xs-4">-->
                            <!--{{ form.acomptettc.label_tag }}-->
                            <!--<div class="input-group">-->
                                <!--{{ form.acomptettc }}-->
                                <!--<div class="input-group-addon">€</div>-->
                            <!--</div>-->
                        <!--</div>-->
                        <!--<div class="col-xs-4">-->
                            <!--{{ form.prixttc.label_tag }}-->
                            <!--<div class="input-group">-->
                                <!--{{ form.prixttc }}-->
                                <!--<div class="input-group-addon">€</div>-->
                            <!--</div>-->
                        <!--</div>-->
                    <!--</div>-->
                    <!--<div class="form-group row">-->
                        <!--<div class="col-xs-4">-->
                            <!--{{ form.dejaregle.label_tag }}-->
                            <!--<div class="input-group">-->
                                <!--{{ form.dejaregle }}-->
                                <!--<div class="input-group-addon">€</div>-->
                            <!--</div>-->
                        <!--</div>-->
                        <!--<div class="col-xs-4">-->
                             <!--{{ form.parttva.label_tag }}-->
                            <!--<div class="input-group">-->
                                <!--{{ form.parttva }}-->
                                <!--<div class="input-group-addon">€</div>-->
                            <!--</div>-->
                        <!--</div>-->
                    <!--</div>-->
                    <!--<div class="form-group row">-->
                        <!--<div class="col-xs-4">-->
                            <!--{{ form.tva.label_tag }}-->
                            <!--<div class="input-group">-->
                                <!--{{ form.tva }}-->
                                <!--<div class="input-group-addon">%</div>-->
                            <!--</div>-->
                        <!--</div>-->
                        <!--<div class="col-xs-4">-->
                            <!--{{ form.netapayer.label_tag }}-->
                            <!--<div class="input-group">-->
                                <!--{{ form.netapayer }}-->
                                <!--<div class="input-group-addon">€</div>-->
                            <!--</div>-->
                        <!--</div>-->
                    <!--</div>-->

                    <div class="form-group">
                        <div class="controls ">
                        <!--<div class="col-sm-10 col-sm-offset-2">-->
                            <a class="btn btn-default" href="{% url 'facture-list' %}">Annuler</a>
                            <button type="submit" class="btn btn-primary">Crééer</button>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block extra_script_content  %}
{{ form.media }}


<script src="{% static 'js/jquery.formset.js' %}"></script>
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'js/locales/bootstrap-datepicker.fr.js' %}"></script>
<script src="{% static 'js/prices_update.js' %}"></script>

<script>
    $('.link-formset').formset({
        prefix:  '{{ devisstep_formset.prefix }}',
        addText: 'Ajouter une étape',
        deleteText: 'Enlever',
        addCssClass: 'btn btn-primary',
        deleteCssClass: 'btn btn-danger',
    });
</script>

<script>

$(document).ready(function(){
  $(function() {
   $('#id_date').datepicker({
        format: "dd/mm/yyyy",
        language: "fr",
        autoclose: true,
        todayHighlight: true
        });
  });
});

$(document).ready(function() {
  $("#id_id_client").change(function(){
    $.ajax({
      // The URL for the request
      url: "/djpgirardin/client-data/",
      // The data to send (will be converted to a query string)
      data: {
          id: $(this).val()
      },
      // Whether this is a POST or GET request
      type: "POST",
      // The type of data we expect back
      dataType : "json",
      // Code to run if the request succeeds;
      // the response is passed to the function
      success: function( json ) {
          $("#id_client_address").val(json.address);
          $("#id_client_cp").val(json.cp);
          $("#id_client_city").val(json.city);
      }
    });
  });
});

</script>

{% endblock %}

minierp/templates/minierp/devis_list.html
{% extends "base-minierp.html" %}

{% block title %}Liste devis{% endblock title %}


{% block extra_head_content %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css">
{% endblock %}

{% block content %}
<!-- Page Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h3>Liste des devis ({{ devis_list.count }})</h3>
      <div class="col-lg-12">
      {% include "messages.html" %}
      {% include "minierp/table_devis.html" %}
        </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block extra_script_content  %}
<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>

<script>
$(document).ready(function() {
  $('#example').DataTable({
  "language": {
      "lengthMenu": "Afficher _MENU_ devis par page",
      "zeroRecords": "Aucuns devis trouvées.",
      "info": "Page affichée _PAGE_ sur _PAGES_",
      "infoEmpty": "Pas de devis disponibles",
      "infoFiltered": "(filtré sur _MAX_ devis)"
      },
  "order": [[ 0, "desc" ]]
  });
} );
</script>
{% endblock %}

minierp/templates/minierp/facture_list.html
{% extends "base-minierp.html" %}

{% block title %}Liste factures{% endblock title %}


{% block extra_head_content %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css">
{% endblock %}

{% block content %}
<!-- Page Content -->
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h3>Liste des factures ({{ facture_list.count }})</h3>
      <div class="col-lg-12">
      {% include "messages.html" %}
      {% include "minierp/table_facture.html" %}
        </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block extra_script_content  %}
<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>

<script>
$(document).ready(function() {
  $('#example').DataTable({
  "language": {
      "lengthMenu": "Afficher _MENU_ factures par page",
      "zeroRecords": "Aucunes factures trouvées.",
      "info": "Page affichée _PAGE_ sur _PAGES_",
      "infoEmpty": "Pas de factures disponibles",
      "infoFiltered": "(filtré sur _MAX_ factures)"
      },
  "order": [[ 0, "desc" ]]
  });
} );
</script>
{% endblock %}

minierp/templates/minierp/obj_delete.html
{% extends "base-minierp.html" %}

{% block title %}Suppression client{% endblock title %}

{% block content %}        
  <!-- Page Content -->
  <div class="container">
      <div class="page-header">
          <div class="row">
              <div class="col-lg-12">
                  <h3>Êtes-vous sûr de vouloir supprimer ce client ?</h3>
                  <p>{{ obj }} </p>
                  <form method="post" action="">
                    {% csrf_token %}
                  <input type="submit" class="btn btn-danger" value="Supprimer" /> <a type="button" href="{% url 'client-list' %}" class="btn btn-default">Annuler</a>
                  </form>
              </div>
          </div>
      </div>
  </div>
{% endblock content %}